name: Build and Push CyberChef

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Build CyberChef
              run: npm run build

            - name: Create build directory
              run: mkdir -p build

            - name: Copy built files to build directory
              run: cp -r dist/* build/

            - name: Commit and push built files
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "action@github.com"
                  git add build/
                  git commit -m "Build CyberChef"
                  git push
